apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-db
  labels:
    app: shopping-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-db
  template:
    metadata:
      labels:
        app: shopping-db
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "shopping_db"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          emptyDir: {}  # Use PersistentVolumeClaim for production

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-db
spec:
  selector:
    app: shopping-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432