name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      #- name: Run Tests
      #  run: pytest

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t shopping-app:latest .

  #deploy:
  #  runs-on: ubuntu-latest
  #  needs: build
#
 #   steps:
      #- name: Deploy to Production
  #      run: |
   #       docker tag shopping-app:latest registry.example.com/shopping-app:latest
    #      docker push registry.example.com/shopping-app:latest
     #     ssh user@production-server "docker pull registry.example.com/shopping-app:latest && docker-compose up -d"
